# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            R4stl1n
tagline:          'The Pub'
description:      'Network Security and Programming words.'
url:              http://r4stl1n.github.io
baseurl:          /

author:
  name:           'Raynaldo Rivera'
  url:            https://twitter.com/r4stl1n

paginate:         10

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/r4stl1n
