# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 5 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
google_analytics: UA-58032713-1

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: R4stl1n's Pub

description: Network Security and Programming words
author:
  name: r4stl1n
  email: royal.r4stl1n@gmail.com
  github: r4stl1n
  twitter: r4stl1n
  linkedin: raynaldorivera
  bio: Network Security and Programming words.
  email_md5: 82dbf7ee965b5802c0ff3939f2544f5f

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
about_path: about.html
archive_path: archive.html
wargames_path: wargames.html

BASE_PATH:
